version: "2"

run:
  timeout: 5m
  go: "1.21"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
  exclusions:
    generated: lax
    paths:
      - _test\.go

formatters:
  enable:
    - gofmt

settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  misspell:
    locale: US

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
